/**
 * Amp Context Schemas - Structured schemas for MCP-compatible context output
 *
 * This module defines the Schema definitions for Amp AI coding agent context files.
 * These schemas ensure type-safe validation and transformation of migration state
 * that persists across Amp coding sessions.
 *
 * @module @effect-migrate/core/schema/amp
 * @since 0.1.0
 */

import * as Schema from "effect/Schema"
import { Semver } from "./common.js"

/**
 * Rule result schema matching RuleResult from @effect-migrate/core.
 *
 * Defines the structure of a single migration rule violation or finding,
 * including location information, severity, and documentation references.
 *
 * @category Schema
 * @since 0.1.0
 */
export const RuleResultSchema = Schema.Struct({
  /** Unique rule identifier */
  id: Schema.String,
  /** Rule type (pattern, boundary, etc.) */
  ruleKind: Schema.String,
  /** Severity level */
  severity: Schema.Literal("error", "warning", "info"),
  /** Human-readable message */
  message: Schema.String,
  /** File path where violation occurred */
  file: Schema.optional(Schema.String),
  /** Line and column range */
  range: Schema.optional(Schema.Struct({
    start: Schema.Struct({
      line: Schema.Number,
      column: Schema.Number
    }),
    end: Schema.Struct({
      line: Schema.Number,
      column: Schema.Number
    })
  })),
  /** Documentation URL */
  docsUrl: Schema.optional(Schema.String),
  /** Rule tags */
  tags: Schema.optional(Schema.Array(Schema.String))
})

/**
 * Thread reference schema for tracking Amp threads where migration work occurred.
 *
 * Captures metadata about Amp coding sessions, including thread URLs, timestamps,
 * and which files/rules were addressed. Used to build an audit trail of migration
 * work across multiple coding sessions.
 *
 * @category Schema
 * @since 0.1.0
 * TODO: Is this still planned or have we completed?
 * @planned Will be populated by `effect-migrate thread add` command
 */
export const ThreadReference = Schema.Struct({
  /** Thread URL in format: https://ampcode.com/threads/T-{uuid} */
  url: Schema.String.pipe(
    Schema.pattern(/^https:\/\/ampcode\.com\/threads\/T-[a-f0-9-]+$/)
  ),
  /** ISO timestamp when thread was created or linked */
  timestamp: Schema.DateTimeUtc,
  /** User-provided description of work done in this thread */
  description: Schema.optional(Schema.String),
  /** Files modified in this thread */
  filesChanged: Schema.optional(Schema.Array(Schema.String)),
  /** Rule IDs resolved or addressed in this thread */
  rulesResolved: Schema.optional(Schema.Array(Schema.String)),
  /** Tags for categorizing threads */
  tags: Schema.optional(Schema.Array(Schema.String)),
  /** Scope filter for grouping threads */
  scope: Schema.optional(Schema.Array(Schema.String))
})

/**
 * Summary statistics for migration findings.
 *
 * Provides high-level metrics about the migration state, including counts of
 * errors, warnings, affected files, and total findings. Used for quick assessment
 * of migration progress and health.
 *
 * @category Schema
 * @since 0.1.0
 */
export const FindingsSummary = Schema.Struct({
  /** Number of error-severity findings */
  errors: Schema.Number,
  /** Number of warning-severity findings */
  warnings: Schema.Number,
  /** Total number of files with findings */
  totalFiles: Schema.Number,
  /** Total number of findings across all files */
  totalFindings: Schema.Number
})

/**
 * Configuration snapshot included in context output.
 *
 * Captures the subset of configuration that's relevant to understanding the
 * audit results, including which rules were active and what failure criteria
 * were applied.
 *
 * @category Schema
 * @since 0.1.0
 */
export const ConfigSnapshot = Schema.Struct({
  /** Rule IDs that produced findings */
  rulesEnabled: Schema.Array(Schema.String),
  /** Severity levels that cause audit failure */
  failOn: Schema.Array(Schema.String)
})

/**
 * Grouped findings by file and by rule.
 *
 * Organizes migration findings in two different views:
 * - By file: All findings for a given file grouped together
 * - By rule: All instances of a specific rule violation grouped together
 *
 * This dual grouping enables both file-centric and rule-centric analysis.
 *
 * @category Schema
 * @since 0.1.0
 */
export const FindingsGroup = Schema.Struct({
  /** Findings grouped by file path (relative to project root, POSIX-style) */
  byFile: Schema.Record({ key: Schema.String, value: Schema.Array(RuleResultSchema) }),
  /** Findings grouped by rule ID */
  byRule: Schema.Record({ key: Schema.String, value: Schema.Array(RuleResultSchema) }),
  /** Summary statistics */
  summary: FindingsSummary
})

/**
 * Complete audit context schema.
 *
 * The primary schema for audit.json files generated by effect-migrate.
 * Contains all information needed to understand the current migration state,
 * including findings, configuration, and optional thread references.
 *
 * @category Schema
 * @since 0.1.0
 */
export const AmpAuditContext = Schema.Struct({
  /** Version of audit.json format */
  schemaVersion: Semver,
  /** Audit revision number (incremented on each write) */
  revision: Schema.Number.pipe(
    Schema.int(),
    Schema.greaterThanOrEqualTo(1)
  ),
  /** effect-migrate tool version */
  toolVersion: Schema.String,
  /** Project root directory (relative, defaults to ".") */
  projectRoot: Schema.String,
  /** ISO timestamp when context was generated */
  timestamp: Schema.DateTimeUtc,
  /** Grouped findings */
  findings: FindingsGroup,
  /** Config snapshot */
  config: ConfigSnapshot,
  /** Thread references (future feature) */
  threads: Schema.optional(Schema.Array(ThreadReference))
})

/**
 * Index schema that points to other context files.
 *
 * The index.json file serves as an entry point to the Amp context directory,
 * providing pointers to all generated files (audit.json, metrics.json, etc.).
 * All artifacts share the same schema version for simplicity.
 *
 * @category Schema
 * @since 0.1.0
 */
export const AmpContextIndex = Schema.Struct({
  /** Schema version for all artifacts (single unified version) */
  schemaVersion: Semver,
  /** effect-migrate tool version */
  toolVersion: Schema.String,
  /** Project root directory (relative, defaults to ".") */
  projectRoot: Schema.String,
  /** ISO timestamp when index was generated */
  timestamp: Schema.DateTimeUtc,
  /** Relative paths to context files */
  files: Schema.Struct({
    /** Path to audit.json */
    audit: Schema.String,
    /** Path to metrics.json (future) */
    metrics: Schema.optional(Schema.String),
    /** Path to badges.md */
    badges: Schema.optional(Schema.String),
    /** Path to threads.json (present when threads exist) */
    threads: Schema.optional(Schema.String)
  })
})

/**
 * Thread entry schema for threads.json.
 *
 * Each entry represents an Amp thread URL where migration work occurred,
 * with optional metadata for categorization and filtering.
 *
 * @category Schema
 * @since 0.2.0
 */
export const ThreadEntry = Schema.Struct({
  id: Schema.String,
  url: Schema.String.pipe(
    Schema.pattern(
      /^https:\/\/ampcode\.com\/threads\/T-[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/
    )
  ),
  createdAt: Schema.DateTimeUtc,
  tags: Schema.optional(Schema.Array(Schema.String)),
  scope: Schema.optional(Schema.Array(Schema.String)),
  description: Schema.optional(Schema.String)
})

/**
 * Threads file schema for threads.json.
 *
 * Root structure containing version and array of thread entries.
 * Threads are sorted by createdAt descending (newest first).
 *
 * **Note:** The `version` field tracks the audit version these threads
 * are associated with, NOT a schema version for threads.json itself.
 * This version should match the audit.json version from context-writer.
 *
 * @category Schema
 * @since 0.2.0
 */
export const ThreadsFile = Schema.Struct({
  version: Schema.Number,
  threads: Schema.Array(ThreadEntry)
})

/**
 * Metrics summary schema.
 *
 * Aggregated statistics about migration progress and violation counts.
 *
 * @category Schema
 * @since 0.2.0
 */
export const MetricsSummary = Schema.Struct({
  /** Total violations across all rules */
  totalViolations: Schema.Number,
  /** Error-level violations */
  errors: Schema.Number,
  /** Warning-level violations */
  warnings: Schema.Number,
  /** Number of files with violations */
  filesAffected: Schema.Number,
  /** Migration completion percentage (0-100) */
  progressPercentage: Schema.Number
})

/**
 * Per-rule metrics schema.
 *
 * Breakdown of violations by individual rule.
 *
 * @category Schema
 * @since 0.2.0
 */
export const RuleMetrics = Schema.Struct({
  /** Rule ID */
  id: Schema.String,
  /** Number of violations */
  violations: Schema.Number,
  /** Severity level */
  severity: Schema.Literal("error", "warning", "info"),
  /** Files affected by this rule */
  filesAffected: Schema.Number
})

/**
 * Complete metrics context schema.
 *
 * Full metrics output including summary, per-rule breakdown, and optional goals.
 *
 * @category Schema
 * @since 0.2.0
 */
export const AmpMetricsContext = Schema.Struct({
  /** Context version */
  version: Schema.Number,
  /** Tool version */
  toolVersion: Schema.String,
  /** Project root path */
  projectRoot: Schema.String,
  /** Timestamp */
  timestamp: Schema.DateTimeUtc,
  /** Summary metrics */
  summary: MetricsSummary,
  /** Per-rule breakdown */
  ruleBreakdown: Schema.Array(RuleMetrics),
  /** Migration goals (future) */
  goals: Schema.optional(Schema.Struct({
    targetDate: Schema.optional(Schema.DateTimeUtc),
    targetProgress: Schema.optional(Schema.Number)
  }))
})

/**
 * Extract TypeScript types from schemas.
 *
 * These type exports enable consumers to use the inferred TypeScript types
 * from the Schema definitions without needing to extract them manually.
 *
 * @category Types
 * @since 0.1.0
 */
export type AmpAuditContext = Schema.Schema.Type<typeof AmpAuditContext>
export type AmpContextIndex = Schema.Schema.Type<typeof AmpContextIndex>
export type ThreadReference = Schema.Schema.Type<typeof ThreadReference>
export type ThreadEntry = Schema.Schema.Type<typeof ThreadEntry>
export type ThreadsFile = Schema.Schema.Type<typeof ThreadsFile>
export type MetricsSummary = Schema.Schema.Type<typeof MetricsSummary>
export type RuleMetrics = Schema.Schema.Type<typeof RuleMetrics>
export type AmpMetricsContext = Schema.Schema.Type<typeof AmpMetricsContext>
